namespace Bootstrap5OffCanvasExample.Classes;

public class MockedData
{
    public static List<string> SentenceList()
    {

        List<string> list = new()
        {
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Cras sed felis eget velit aliquet. Semper quis lectus nulla at volutpat diam ut. Purus sit amet volutpat consequat mauris nunc congue nisi vitae. Consectetur a erat nam at lectus urna duis convallis convallis. Viverra orci sagittis eu volutpat odio facilisis mauris. Suspendisse potenti nullam ac tortor vitae purus. Egestas tellus rutrum tellus pellentesque. At auctor urna nunc id cursus metus aliquam. Diam quis enim lobortis scelerisque fermentum dui faucibus in ornare. Rhoncus mattis rhoncus urna neque. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Elementum nisi quis eleifend quam adipiscing vitae. Enim ut sem viverra aliquet eget sit amet tellus. Quis auctor elit sed vulputate mi sit. Turpis egestas sed tempus urna et pharetra pharetra massa. Dignissim diam quis enim lobortis scelerisque fermentum dui faucibus in. In fermentum posuere urna nec tincidunt praesent semper feugiat. Tellus mauris a diam maecenas sed.",
            "A diam maecenas sed enim. Risus pretium quam vulputate dignissim suspendisse in est ante in. Amet tellus cras adipiscing enim eu turpis. Pellentesque habitant morbi tristique senectus et netus. Tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras fermentum. Eros donec ac odio tempor orci dapibus ultrices in iaculis. Sed elementum tempus egestas sed sed. Varius quam quisque id diam vel quam. Sapien faucibus et molestie ac feugiat sed. Viverra nibh cras pulvinar mattis nunc sed blandit libero volutpat. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Nisi lacus sed viverra tellus in hac habitasse platea. Tristique magna sit amet purus gravida quis blandit.",
            "Feugiat in fermentum posuere urna nec tincidunt praesent. At varius vel pharetra vel turpis nunc eget lorem dolor. Nisl nisi scelerisque eu ultrices. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi. Quam id leo in vitae turpis massa sed elementum. Pharetra magna ac placerat vestibulum. Maecenas ultricies mi eget mauris. Turpis egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Diam in arcu cursus euismod quis viverra nibh cras. Ullamcorper eget nulla facilisi etiam. Quam id leo in vitae turpis massa sed elementum. Sed vulputate mi sit amet. Sed risus pretium quam vulputate dignissim suspendisse. At volutpat diam ut venenatis tellus in. Feugiat vivamus at augue eget arcu dictum. Pellentesque nec nam aliquam sem et tortor consequat id. Posuere ac ut consequat semper viverra nam libero. Pulvinar mattis nunc sed blandit libero volutpat sed cras ornare. Nisi scelerisque eu ultrices vitae auctor eu.",
            "Nibh nisl condimentum id venenatis. Tortor vitae purus faucibus ornare suspendisse. Malesuada pellentesque elit eget gravida cum sociis. Sit amet risus nullam eget felis eget nunc. Varius morbi enim nunc faucibus. Mus mauris vitae ultricies leo integer malesuada nunc vel. Platea dictumst quisque sagittis purus. Curabitur vitae nunc sed velit dignissim. Nulla porttitor massa id neque aliquam. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu. Arcu vitae elementum curabitur vitae nunc sed velit. Posuere lorem ipsum dolor sit amet.",
            "Id velit ut tortor pretium viverra suspendisse potenti. Ut lectus arcu bibendum at varius vel pharetra vel turpis. Nunc non blandit massa enim nec dui. Non pulvinar neque laoreet suspendisse interdum. Lectus quam id leo in vitae turpis massa. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Varius vel pharetra vel turpis nunc eget. Sed blandit libero volutpat sed cras ornare arcu dui. Suspendisse in est ante in. Consectetur purus ut faucibus pulvinar elementum integer enim. Purus gravida quis blandit turpis cursus in hac. Maecenas accumsan lacus vel facilisis. Congue mauris rhoncus aenean vel elit scelerisque.",
            "Pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Malesuada fames ac turpis egestas integer eget aliquet nibh. Eget mi proin sed libero enim sed faucibus turpis. Aenean et tortor at risus viverra adipiscing. Ultrices sagittis orci a scelerisque purus semper eget duis. Fringilla urna porttitor rhoncus dolor purus non enim. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce. Nulla facilisi morbi tempus iaculis urna id volutpat. Aliquet bibendum enim facilisis gravida neque convallis a cras semper. Eu turpis egestas pretium aenean pharetra magna. Nullam ac tortor vitae purus faucibus ornare suspendisse sed nisi. Magna fringilla urna porttitor rhoncus. Dui vivamus arcu felis bibendum ut. Tempor orci dapibus ultrices in. Est ultricies integer quis auctor elit sed vulputate mi. Non sodales neque sodales ut etiam sit amet nisl purus. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt.",
            "Duis ut diam quam nulla porttitor. Convallis tellus id interdum velit laoreet id donec. Sit amet justo donec enim diam. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Vitae proin sagittis nisl rhoncus mattis. Tempor commodo ullamcorper a lacus vestibulum. Pharetra sit amet aliquam id diam. Condimentum vitae sapien pellentesque habitant morbi tristique. Imperdiet dui accumsan sit amet nulla facilisi morbi. Diam donec adipiscing tristique risus nec feugiat. Tellus integer feugiat scelerisque varius morbi enim. Ante in nibh mauris cursus. Eu lobortis elementum nibh tellus molestie nunc non blandit. Id nibh tortor id aliquet lectus proin nibh nisl condimentum. Pellentesque id nibh tortor id aliquet lectus proin. Massa ultricies mi quis hendrerit dolor. Aliquet sagittis id consectetur purus ut. Placerat orci nulla pellentesque dignissim enim sit amet. Cursus turpis massa tincidunt dui ut.",
            "Vitae et leo duis ut. Mauris in aliquam sem fringilla ut. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Amet aliquam id diam maecenas ultricies mi. Hendrerit dolor magna eget est. In hac habitasse platea dictumst. Amet purus gravida quis blandit turpis cursus in hac. Mi quis hendrerit dolor magna. Vehicula ipsum a arcu cursus vitae. Nunc non blandit massa enim nec. Fames ac turpis egestas maecenas. Egestas maecenas pharetra convallis posuere morbi. Id donec ultrices tincidunt arcu non sodales neque sodales ut. Semper risus in hendrerit gravida rutrum quisque. Cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Porttitor leo a diam sollicitudin tempor. Purus semper eget duis at tellus. Arcu cursus euismod quis viverra nibh cras."
        };


        return list;
    }
}
